### ISSUE TITLE
Legend text wrapping

### ISSUE THREAD

**Issue by swiftraptor** [swiftraptor/mapviz#3]
Investigate https://github.com/plouc/nivo/issues/433

**Comment by swiftraptor** [comment]
fixed legend issues by improving chart UI

**Comment by kevbost** [comment]
Hey @swiftraptor, did you figure out legend wrapping? Found this issue via https://github.com/plouc/nivo/issues/433

**Comment by swiftraptor** [comment]
Hi @kevbost 
Thanks for the link to the github issue - I never did get onto legend wrapping, just rejigged a bit of css so the text would display all on one line
